sudo: required
node_js:
  - 8
services:
  - docker

before_install:
  # run the dev dockerfile in the client folder to build image that can run tests and the build context is the nested client folder:
  - docker build -t brentgrammer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brentgrammer/react-test npm test -- --coverage
# build prod images for each service/project (name the images with -t anything you want but be consistent)
# this will use the Dockerfile files so no need for the -f to use the dev file as above
after_success:
  - docker build -t brentgrammer/multi-client ./client
  - docker build -t brentgrammer/multi-nginx ./nginx
  - docker build -t brentgrammer/multi-server ./server
  - docker build -t brentgrammer/multi-worker ./worker
  # log in to Docker Hub via CLI
  # retrieve password from env variable set on Travis CI and pipe it as an input to the next command / standard in (stdin) channel
  # the --password-stdin tells docker login to expect to receive that password over the stdin channel
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub:
  - docker push brentgrammer/multi-client
  - docker push brentgrammer/multi-nginx
  - docker push brentgrammer/multi-server
  - docker push brentgrammer/multi-worker