sudo: required
services:
  - docker

before_install:
  - docker build -t brentgrammer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run brentgrammer/react-test npm test -- --coverage
after_success:
  - docker build -t brentgrammer/multi-client ./client
  - docker build -t brentgrammer/multi-nginx ./nginx
  - docker build -t brentgrammer/multi-server ./server
  - docker build -t brentgrammer/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push brentgrammer/multi-client
  - docker push brentgrammer/multi-nginx
  - docker push brentgrammer/multi-server
  - docker push brentgrammer/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1 
  app: multi-docker 
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-253160347010
  bucket_path: multi-docker
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
